# Generated by Django 2.2.4 on 2019-08-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
