# Generated by Django 2.2.4 on 2019-08-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp1', '0002_auto_20190809_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('fav', models.IntegerField()),
                ('degree', models.IntegerField()),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
            ],
        ),
    ]
